name: 'technosweb'
services:
  frontend-app:
    container_name: frontend
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - technosweb_net

networks:
  technosweb_net:
